name: Release (generar binarios)

on:
  release:
    types:
      - created

permissions:
  contents: write

env:
  CRATE_NAME: link_inspector
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  test:
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: link_inspector
            name: link_inspector-Linux-x86_64-musl.tar.gz
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: link_inspector.exe
            name: link_inspector-Windows-x86_64.zip
          - os_name: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: link_inspector
            name: link_inspector-Darwin-x86_64.tar.gz
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Configure Git
        run: |
          git config --global user.email "antikorps@gmail.com"
          git config --global user.name "antikorps"
      - name: Install dependencies on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools libssl-dev pkg-config
        if: contains(matrix.platform.os_name, 'Linux')
      - name: Set OpenSSL directory
        run: echo "OPENSSL_DIR=/usr/lib/ssl" >> $GITHUB_ENV
        if: matrix.platform.os == 'Linux'
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../.
